// <auto-generated /> 
namespace Rena.Mathematics;

public partial struct Vec3<TNumber>
{
    #region Vec2 Swizzling
    public Vec2<TNumber> Xx
        => new(X, X);

    public Vec2<TNumber> Xy
        => new(X, Y);

    public Vec2<TNumber> Xz
        => new(X, Z);

    public Vec2<TNumber> Yx
        => new(Y, X);

    public Vec2<TNumber> Yy
        => new(Y, Y);

    public Vec2<TNumber> Yz
        => new(Y, Z);

    public Vec2<TNumber> Zx
        => new(Z, X);

    public Vec2<TNumber> Zy
        => new(Z, Y);

    public Vec2<TNumber> Zz
        => new(Z, Z);
    #endregion

    #region Vec3 Swizzling
    public Vec3<TNumber> Xxx
        => new(X, X, X);

    public Vec3<TNumber> Xxy
        => new(X, X, Y);

    public Vec3<TNumber> Xxz
        => new(X, X, Z);

    public Vec3<TNumber> Xyx
        => new(X, Y, X);

    public Vec3<TNumber> Xyy
        => new(X, Y, Y);

    public Vec3<TNumber> Xyz
        => new(X, Y, Z);

    public Vec3<TNumber> Xzx
        => new(X, Z, X);

    public Vec3<TNumber> Xzy
        => new(X, Z, Y);

    public Vec3<TNumber> Xzz
        => new(X, Z, Z);

    public Vec3<TNumber> Yxx
        => new(Y, X, X);

    public Vec3<TNumber> Yxy
        => new(Y, X, Y);

    public Vec3<TNumber> Yxz
        => new(Y, X, Z);

    public Vec3<TNumber> Yyx
        => new(Y, Y, X);

    public Vec3<TNumber> Yyy
        => new(Y, Y, Y);

    public Vec3<TNumber> Yyz
        => new(Y, Y, Z);

    public Vec3<TNumber> Yzx
        => new(Y, Z, X);

    public Vec3<TNumber> Yzy
        => new(Y, Z, Y);

    public Vec3<TNumber> Yzz
        => new(Y, Z, Z);

    public Vec3<TNumber> Zxx
        => new(Z, X, X);

    public Vec3<TNumber> Zxy
        => new(Z, X, Y);

    public Vec3<TNumber> Zxz
        => new(Z, X, Z);

    public Vec3<TNumber> Zyx
        => new(Z, Y, X);

    public Vec3<TNumber> Zyy
        => new(Z, Y, Y);

    public Vec3<TNumber> Zyz
        => new(Z, Y, Z);

    public Vec3<TNumber> Zzx
        => new(Z, Z, X);

    public Vec3<TNumber> Zzy
        => new(Z, Z, Y);

    public Vec3<TNumber> Zzz
        => new(Z, Z, Z);
    #endregion

    #region Vec4 Swizzling
    public Vec4<TNumber> Xxxx
        => new(X, X, X, X);

    public Vec4<TNumber> Xxxy
        => new(X, X, X, Y);

    public Vec4<TNumber> Xxxz
        => new(X, X, X, Z);

    public Vec4<TNumber> Xxyx
        => new(X, X, Y, X);

    public Vec4<TNumber> Xxyy
        => new(X, X, Y, Y);

    public Vec4<TNumber> Xxyz
        => new(X, X, Y, Z);

    public Vec4<TNumber> Xxzx
        => new(X, X, Z, X);

    public Vec4<TNumber> Xxzy
        => new(X, X, Z, Y);

    public Vec4<TNumber> Xxzz
        => new(X, X, Z, Z);

    public Vec4<TNumber> Xyxx
        => new(X, Y, X, X);

    public Vec4<TNumber> Xyxy
        => new(X, Y, X, Y);

    public Vec4<TNumber> Xyxz
        => new(X, Y, X, Z);

    public Vec4<TNumber> Xyyx
        => new(X, Y, Y, X);

    public Vec4<TNumber> Xyyy
        => new(X, Y, Y, Y);

    public Vec4<TNumber> Xyyz
        => new(X, Y, Y, Z);

    public Vec4<TNumber> Xyzx
        => new(X, Y, Z, X);

    public Vec4<TNumber> Xyzy
        => new(X, Y, Z, Y);

    public Vec4<TNumber> Xyzz
        => new(X, Y, Z, Z);

    public Vec4<TNumber> Xzxx
        => new(X, Z, X, X);

    public Vec4<TNumber> Xzxy
        => new(X, Z, X, Y);

    public Vec4<TNumber> Xzxz
        => new(X, Z, X, Z);

    public Vec4<TNumber> Xzyx
        => new(X, Z, Y, X);

    public Vec4<TNumber> Xzyy
        => new(X, Z, Y, Y);

    public Vec4<TNumber> Xzyz
        => new(X, Z, Y, Z);

    public Vec4<TNumber> Xzzx
        => new(X, Z, Z, X);

    public Vec4<TNumber> Xzzy
        => new(X, Z, Z, Y);

    public Vec4<TNumber> Xzzz
        => new(X, Z, Z, Z);

    public Vec4<TNumber> Yxxx
        => new(Y, X, X, X);

    public Vec4<TNumber> Yxxy
        => new(Y, X, X, Y);

    public Vec4<TNumber> Yxxz
        => new(Y, X, X, Z);

    public Vec4<TNumber> Yxyx
        => new(Y, X, Y, X);

    public Vec4<TNumber> Yxyy
        => new(Y, X, Y, Y);

    public Vec4<TNumber> Yxyz
        => new(Y, X, Y, Z);

    public Vec4<TNumber> Yxzx
        => new(Y, X, Z, X);

    public Vec4<TNumber> Yxzy
        => new(Y, X, Z, Y);

    public Vec4<TNumber> Yxzz
        => new(Y, X, Z, Z);

    public Vec4<TNumber> Yyxx
        => new(Y, Y, X, X);

    public Vec4<TNumber> Yyxy
        => new(Y, Y, X, Y);

    public Vec4<TNumber> Yyxz
        => new(Y, Y, X, Z);

    public Vec4<TNumber> Yyyx
        => new(Y, Y, Y, X);

    public Vec4<TNumber> Yyyy
        => new(Y, Y, Y, Y);

    public Vec4<TNumber> Yyyz
        => new(Y, Y, Y, Z);

    public Vec4<TNumber> Yyzx
        => new(Y, Y, Z, X);

    public Vec4<TNumber> Yyzy
        => new(Y, Y, Z, Y);

    public Vec4<TNumber> Yyzz
        => new(Y, Y, Z, Z);

    public Vec4<TNumber> Yzxx
        => new(Y, Z, X, X);

    public Vec4<TNumber> Yzxy
        => new(Y, Z, X, Y);

    public Vec4<TNumber> Yzxz
        => new(Y, Z, X, Z);

    public Vec4<TNumber> Yzyx
        => new(Y, Z, Y, X);

    public Vec4<TNumber> Yzyy
        => new(Y, Z, Y, Y);

    public Vec4<TNumber> Yzyz
        => new(Y, Z, Y, Z);

    public Vec4<TNumber> Yzzx
        => new(Y, Z, Z, X);

    public Vec4<TNumber> Yzzy
        => new(Y, Z, Z, Y);

    public Vec4<TNumber> Yzzz
        => new(Y, Z, Z, Z);

    public Vec4<TNumber> Zxxx
        => new(Z, X, X, X);

    public Vec4<TNumber> Zxxy
        => new(Z, X, X, Y);

    public Vec4<TNumber> Zxxz
        => new(Z, X, X, Z);

    public Vec4<TNumber> Zxyx
        => new(Z, X, Y, X);

    public Vec4<TNumber> Zxyy
        => new(Z, X, Y, Y);

    public Vec4<TNumber> Zxyz
        => new(Z, X, Y, Z);

    public Vec4<TNumber> Zxzx
        => new(Z, X, Z, X);

    public Vec4<TNumber> Zxzy
        => new(Z, X, Z, Y);

    public Vec4<TNumber> Zxzz
        => new(Z, X, Z, Z);

    public Vec4<TNumber> Zyxx
        => new(Z, Y, X, X);

    public Vec4<TNumber> Zyxy
        => new(Z, Y, X, Y);

    public Vec4<TNumber> Zyxz
        => new(Z, Y, X, Z);

    public Vec4<TNumber> Zyyx
        => new(Z, Y, Y, X);

    public Vec4<TNumber> Zyyy
        => new(Z, Y, Y, Y);

    public Vec4<TNumber> Zyyz
        => new(Z, Y, Y, Z);

    public Vec4<TNumber> Zyzx
        => new(Z, Y, Z, X);

    public Vec4<TNumber> Zyzy
        => new(Z, Y, Z, Y);

    public Vec4<TNumber> Zyzz
        => new(Z, Y, Z, Z);

    public Vec4<TNumber> Zzxx
        => new(Z, Z, X, X);

    public Vec4<TNumber> Zzxy
        => new(Z, Z, X, Y);

    public Vec4<TNumber> Zzxz
        => new(Z, Z, X, Z);

    public Vec4<TNumber> Zzyx
        => new(Z, Z, Y, X);

    public Vec4<TNumber> Zzyy
        => new(Z, Z, Y, Y);

    public Vec4<TNumber> Zzyz
        => new(Z, Z, Y, Z);

    public Vec4<TNumber> Zzzx
        => new(Z, Z, Z, X);

    public Vec4<TNumber> Zzzy
        => new(Z, Z, Z, Y);

    public Vec4<TNumber> Zzzz
        => new(Z, Z, Z, Z);
    #endregion
}